[package]
name = "rate-limiter-core"
version = "0.1.0"
edition = "2021"
authors = ["KuanLinChen <kuan.lyn.chen@gmail.com>"]
description = "Rate limiting library with multiple thread-safe algorithms"
license = "MIT"
repository = "https://github.com/kuanlin/rate_limiter_core"
documentation = "https://docs.rs/rate-limiter-core"
homepage = "https://github.com/kuanlin/rate_limiter_core"
readme = "README.md"
keywords = ["rate-limiting", "throttling", "concurrency", "algorithms", "rate-limiter"]
categories = [
    "algorithms", 
    "concurrency", 
    "network-programming",
    "asynchronous"  
]
rust-version = "1.60"

[dependencies]

[dev-dependencies]

[features]
default = []

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]